### ISSUE TITLE
Why is sys.executable wrapped in os.path.basename?

### ISSUE THREAD

**Issue by dsuch** [plasma-umass/scalene#126]
Hello,

I have just installed scalene 1.1.15 from PyPI using a virtualenv-based Python binary.

I had some difficulties with getting it to run and I pinned it down to the "os.path.basename(sys.executable)" line in the snippet below. For reference, the error message was "/usr/bin/python: No module named scalene".

I believe the assumption here is that the command "python" will always be the one that has scalene on its PYTHONPATH.

However, if my Python installation is in /home/user/projects/myproject/env/bin/python then using basename will trim it to "python" which points to the system-wide Python installation where scalene cannot be found.

I wonder why basename was used in this location? Perhaps it is important to keep it there and I just do not understand it yet, being a new user.

Thank you.

```python
    # Load the shared object on Linux.
    if sys.platform == "linux":
        if ("LD_PRELOAD" not in os.environ) and (
            "PYTHONMALLOC" not in os.environ
        ):
            os.environ["LD_PRELOAD"] = os.path.join(
                os.path.dirname(__file__), "libscalene.so"
            )
            os.environ["PYTHONMALLOC"] = "malloc"
            args = sys.argv[1:]
            args = [
                os.path.basename(sys.executable),
                "-m",
                "scalene",
            ] + args
```

**Comment by emeryberger** [comment]
Sorry for the late response!

This is part of how Scalene ensures that it "follows" any subprocesses, by routing calls that would have gone to straight `python` instead to `Scalene`. I will note that I've used Scalene with virtualenv and it worked fine for me...

**Comment by SyamGadde** [comment]
Can I resurrect this?  Wouldn't removing the basename() call and just using sys.executable still accomplish that, as well as allow it to work with python executables that are not (first) on the PATH?  I use virtualenv just as the original poster describes (without "activating" it -- just calling the virtualenv python executable) and instead of using the same python executable, scalene tries to execute the standard python which doesn't have scalene installed.

Removing the basename() call in the above case gets scalene to work again, but I have not tried with subprocesses.

**Comment by RuRo** [comment]
Agreed. The current behaviour is incorrect. Consider the following script:
```python
import sys
print(sys.executable)
print()

import platform

print(platform.platform())
```

Running this script with `python script.py`:
```
/usr/bin/python

Linux-5.4.0-92-generic-x86_64-with-glibc2.29
```
With  `/usr/bin/python3 script.py`:
```
/usr/bin/python3

Linux-5.4.0-92-generic-x86_64-with-glibc2.29
```
With `/some/custom/python script.py`:
```
/some/custom/python

Linux-5.4.0-92-generic-x86_64-with-glibc2.29
```

Note, that the absolute path to the interpreter is printed even when just "`python`" is used on the CLI.

However, running this script with `{any_of_the_above_pythons} -m scalene show.py` or `scalene show.py` prints
```
python

Error in program being profiled:
 [Errno 2] No such file or directory: '/home/ruro/scalene_example/python'
Traceback (most recent call last):
  File /home/ruro/.local/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1629, in profile_code
    exec(code, the_globals, the_locals)
  File "show.py", line 7, in <module>
    print(platform.platform())
  File "/usr/lib/python3.8/platform.py", line 1206, in platform
    libcname, libcversion = libc_ver(sys.executable)
  File "/usr/lib/python3.8/platform.py", line 193, in libc_ver
    with open(executable, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruro/scalene_example/python'
Scalene: Program did not run for long enough to profile.
```

This happens because scalene changes `sys.executable` [here](https://github.com/plasma-umass/scalene/blob/f45b3d4aa2ff6c46fcf0eb8eec281207b0ce05bd/scalene/scalene_profiler.py#L680). However, this is not correct, because `sys.executable` must be an absolute path:
![image](https://user-images.githubusercontent.com/3747318/200860476-6264b73a-a605-49c0-8ffb-45366ac9083d.png)

Replacing the above line in `scalene_profiler.py` with
```python
sys.executable = os.path.join(Scalene.__python_alias_dir, Scalene.__all_python_names[0])
```
fixes the issue while keeping the "redirection" semantics.

`scalene show.py`:
```
/tmp/scalene2we7nw7t/python

Linux-5.4.0-92-generic-x86_64-with
Scalene: Program did not run for long enough to profile.
```

**Comment by RuRo** [comment]
Also, you should be aware that `/tmp` is often mounted with `noexec` for security reasons and so running scripts/executables from it may not work even when the correct permissions are set.
