### ISSUE TITLE
Unsupported architecture on MacOS 10.15.7

### ISSUE THREAD

**Issue by gabrielelanaro** [plasma-umass/scalene#249]
I am trying to install scalene from pip using:

```
pip install scalene
```

This is part of the log:

```
    note: '__uint128_t' declared here
    In file included from src/source/get_line_atomic.cpp:2:
    In file included from /opt/anaconda3/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdio.h:107:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wz/64x_y66n3tb4d2jzsglhsgg00000gp/T/pip-install-c7n7won7/scalene/setup.py'"'"'; __file__='"'"'/private/var/folders/wz/64x_y66n3tb4d2jzsglhsgg00000gp/T/pip-install-c7n7won7/scalene/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/wz/64x_y66n3tb4d2jzsglhsgg00000gp/T/pip-record-f2evol_y/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.8/scalene Check the logs for full command output.
```

Useful information:

- MacOS 10.15.7
- Python 3.8.5 (anaconda distribution)
- Scalene version 1.3.12

I have checked out the package locally and the package seems to install and run correctly if I remove the `--arch arm64` from the setup.py

Is there some extra step I should be doing while installing or do you have any suggestions for a fix? I would be happy to open a PR with a fix and contribute to the project

**Comment by jaltmayerpizzorno** [comment]
The actual problem is that `pip` isn't finding (or accepting) the universal binary we publish... what version of `pip` are you using? You could try first upgrading `pip`, i.e., `pip install -U pip` and then re-attempt `pip install scalene`.

If that doesn't work, please run
```
pip uninstall scalene
pip install scalene -v 2>&1 >/tmp/piplog
```
and send us the resulting `/tmp/piplog` file.

As for the build error, the issue on MacOS 10.15 is that some SDK versions get in the way even when Xcode supports `arm64`.  We do build (through github actions) on MacOS 10.15, but (on a virtual machine where this isn't persisted) first remove all SDKs from `/Library/Developer/CommandLineTools/SDKs/`. We could adapt `setup.py` for this, but it wouldn't be easily maintainable, so I'm hoping the `pip` upgrade will solve it for you.

**Comment by gabrielelanaro** [comment]
Upgrading pip worked! thanks for the help!
