### ISSUE TITLE
Cannot use scalene with pipx

### ISSUE THREAD

**Issue by frafra** [plasma-umass/scalene#322]
**Describe the bug**
`No module named scalene` is shown after trying to run scalene following an installation with pipx.

**To Reproduce**
1. `pipx install scalene`
2. `python -m scalene`
3. See error

**Expected behavior**
It should just work, I guess.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Additional context**

```
$ pipx install scalene
  installed package scalene 1.3.16, Python 3.9.7
  These apps are now globally available
    - scalene
done! ✨ 🌟 ✨
$ python3.9 -V
Python 3.9.7
$ python3.9 -m scalene 
/usr/bin/python3.9: No module named scalene
```

**Comment by emeryberger** [comment]
Just as a sanity check: can you try running `pipx` as follows? `python3.9 -m pipx install scalene`? Maybe it's just picking up the wrong Python?

**Comment by sternj** [comment]
ok so this is a weird one. This isn't _quite_ how you need to invoke Scalene under `pipx`. As per [the documentation](https://github.com/pypa/pipx#walkthrough-installing-a-package-and-its-applications-with-pipx), you need to run it just as `scalene` rather than `python3 -m scalene`. I have verified that this works on a Linux instance. I am closing this for now, please reopen if you have any further issues.
