### ISSUE TITLE
elf_dynamic_array_reader.h(64)  tag not found

### ISSUE THREAD

**Issue by IavTavares** [plasma-umass/scalene#502]
**Describe the bug**
When I call `scalene my_script.py`, I get the following error:

**To Reproduce**
1. Create a simple script: 
```
import pandas as pd
ola = pd.DataFrame() 
```
2. Run `scalene my_script.py`
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome

**Comment by emeryberger** [comment]
I expect this is because you are not using the repository version. Please run `python3 -m pip install git+https://github.com/plasma-umass/scalene`. 

Using the repository version, works fine for me on Ubuntu 22.04. Just tried this with the repository version and it was fine. It launched Firefox, not Chrome (and reported some warnings but everything worked). FWIW I am on an M1 and there doesn't appear to be a Chrome download for that architecture.

**Comment by IavTavares** [comment]
Thanks! this seems to have solved it ;)
