### ISSUE TITLE
Contributor documentation

### ISSUE THREAD

**Issue by johanvergeer** [plasma-umass/scalene#69]
**Is your feature request related to a problem? Please describe.**
I would like to contribute to Scalene, but I cannot find any documentation on how to contribute. The Python part is easy, but the rest confuses me quite a bit.

**Describe the solution you'd like**
- Add a Contribute chapter to the README
- Describe how to setup a Python environment
- Describe how to run all the tests
- Describe how to install and use the package locally. (e.g. `pip install -e scalene`)

**Comment by GammaPi** [comment]
The professor's paper is very helpful for me to understand the code.
I'm also working on improving scalene, maybe I could help with writing some detailed documentation?!

**Comment by johanvergeer** [comment]
Thanks @GammaPi for the references. I'll read them in order to get a better sense of what is going on. 

It looks to me like there also is quite some older or "experimental" code in the master branch. I believe it helps a lot when the codebase is clean (and contains sufficient tests) in order to let people contribute.

What are your opinions about that @GammaPi and @emeryberger ?

**Comment by emeryberger** [comment]
Just removed some cruft, which should hopefully help. Note that I am planning some more changes, so it'd be good to try to coordinate.

Testing the profiler itself is tricky, since it's inherently probabilistic in nature. Testing the heap implementation is different, but to be honest, most of the time, a broken heap implementation is going to fail and hard once you try to run it with something like TensorFlow. I just added two test programs, `test/testtf.py` (TensorFlow) and `test/testpyt.py` (PyTorch).

**Comment by emeryberger** [comment]
There are now a variety of test programs. Most cruft has been removed, and the formerly monolithic Scalene profiler has been factored out into a number of much smaller pieces in https://github.com/plasma-umass/scalene/tree/master/scalene. I still don't have a guide to contributing, but I'd welcome a PR!
