### ISSUE TITLE
Add pyroscope to the comparison in the README

### ISSUE THREAD

**Issue by dralley** [plasma-umass/scalene#695]
https://pyroscope.io/
https://github.com/grafana/pyroscope

It's a little unlike the rest of the tools listed because it's a continuous profiler meant to be used in production with integrations with Jaeger and Grafana and so forth, but in terms of features it's fairly competitive as it handles both CPU and memory.

**Comment by emeryberger** [comment]
Pyroscope depends on py-spy for its reporting, which is covered in the table (which is a little out of date vs. the one presented in the paper). Since py-spy does not do memory profiling (as far as I am aware), whatever memory profiling Pyroscope is doing is probably just measuring RSS of the Python process (which isn't actually great, as our paper discusses), though I'd love to hear more details. 

<img width="384" alt="Screenshot 2023-09-15 at 2 01 24 PM" src="https://github.com/plasma-umass/scalene/assets/1612723/44ec104e-85ad-4460-855f-7b16f9a88fb3">

**Comment by emeryberger** [comment]
Closing since I think this resolves the issue, but if not, will re-open.

**Comment by dralley** [comment]
Thanks, you are correct.  Also it appears that the memory tracking doesn't apply to Python.

https://github.com/grafana/pyroscope/issues/316

My apologies, I should have looked a bit deeper first.
