### ISSUE TITLE
Provide more meaningful feedback when Scalene has a "null" profile

### ISSUE THREAD

**Issue by emeryberger** [plasma-umass/scalene#760]
**Is your feature request related to a problem? Please describe.**
Right now, for certain cases, Scalene will output `Scalene: Program did not run for long enough to profile.` but this does not provide diagnostic information.

**Describe the solution you'd like**
[DRAFT] This is a sketch of the solution.

When encountering a null profile:
* if `--profile-all` was _not_ specified, suggest it as a way to profile otherwise excluded code (notably Python libraries, which are excluded by default).
* if `--profile-only` or `--profile-exclude` were specified, suggest that the patterns might be excluding too many files. Collecting the previously filtered out files could allow suggested fixes (as in, remove `foo` because it matches too many files).
* if none of the above cases hold, indicate that Scalene can only profile code that runs for at least one second or allocates some threshold amount of memory (state how much).

**Comment by emeryberger** [comment]
Addresses this discussion: https://github.com/plasma-umass/scalene/discussions/722#discussioncomment-8155248

**Comment by AvdN** [comment]
I think suggesting `--profile-all` if not specified is a good start. If I get too much information, I am likely to try and find out how to cull that. Because there was nothing, I first assumed `scalene` was broken, or at least didn't support my use case.

What was confusing (to me) is the message `Scalene: Program did not run for long enough to profile` when the **program** obviously took minutes to run. So either extending the message pointing to `--profile-XXX` would help, maybe supported by changing `program` to `the specified code part of the program`

**Comment by vtnate** [comment]
Thanks for considering this issue! I came to Scalene because my test gets canceled when running on Github Actions CI, due to too much cpu or RAM (GH doesn't specify which). That led me to Scalene to determine what in my test is taking such a large amount of resources.

Since my code (as seen in the discussion quote) takes well over 1 second to run, and I'm being told by another source (Github Actions) that either my cpu or memory usage is very high (high enough they cancel my test run), I'm surprised at the output of Scalene and my first assumption was user error.

**Comment by emeryberger** [comment]
Hi @vtnate - this may be unrelated; can you please open another issue? Thanks!
