### ISSUE TITLE
scalene memory profiling is slower then memray!

### ISSUE THREAD

**Issue by zdyj3170101136** [plasma-umass/scalene#761]
#### scalene version
scalene==1.3.12

#### python version
3.7.0

#### pip
pip freeze:
```
attrs==23.2.0
cloudpickle==2.2.1
ddtrace==0.56.1
importlib-metadata==6.7.0
Jinja2==3.1.3
linkify-it-py==2.0.2
markdown-it-py==2.2.0
MarkupSafe==2.1.3
mdit-py-plugins==0.3.5
mdurl==0.1.2
memray==1.11.0
numpy==1.21.6
packaging==23.2
Pillow==7.1.0
protobuf==4.24.4
pygments==2.17.2
pynvml==11.5.0
rich==13.7.0
scalene==1.3.12
six==1.16.0
tenacity==8.2.3
textual==0.43.2
typing-extensions==4.7.1
uc-micro-py==1.0.2
zipp==3.15.0
```

#### behaviour
run scalene:
```
 time python3.7 -m scalene --cpu-sampling-rate 0   benchmakr.py
real    0m6.273s
user    0m5.376s
sys     0m1.039s
```

run memray:
```
time python3.7 -m memray run benchmakr.py
real    0m5.741s
user    0m4.609s
sys     0m0.875s
```

raw:
```
time python3.7  benchmakr.py

real    0m4.300s
user    0m3.551s
sys     0m0.739s
```

#### benchmakr.py
use pillow read lots of image:
```
import os
import PIL
from PIL import Image
#import time
dir = "/home/centos/pillow-bench/Images_0/0"
onlyfiles = []

#time.sleep(10)
filedir = dir
files = [f for f in os.listdir(filedir) if os.path.isfile(os.path.join(filedir, f))]
filepaths = map( lambda x: os.path.join(filedir, x), files )
onlyfiles += list(filepaths)

images = []
s = 0
for i in range(len(onlyfiles)):
    fname = onlyfiles[i]
    image = PIL.Image.open(fname)
    # Do something
    images.append(image)
    image.tobytes("xbm", "rgb")
    if i / 10000 == 1:
        print('iteration ', i)
        break

#input("Press Enter to continue...")
```

**Comment by emeryberger** [comment]
I can't run this because you haven't attached the contents of the directory. Please do so.

All this said, Scalene doesn't claim to be faster than memray. In any event, these numbers aren't helpful given that they are for such old versions of Python and Scalene. I'd be interested to see that data for current versions.

It's also important to note that Scalene time includes the time to generate its profile, so you need to add the post-processing for memray as well in order for the comparison to be more fair. All this said, Python 3.12 and later have some improvements that, once we incorporate them, we expect will substantially lower Scalene's overhead.

**Comment by emeryberger** [comment]
Closing for lack of response.
