### ISSUE TITLE
Scalene v1.5.34 does not offer OpenAI suggestion option | CPU and GPU columns are also missing.

### ISSUE THREAD

**Issue by Zia-** [plasma-umass/scalene#773]
I'm running my script like this:

`venv_env/bin/scalene--reduced-profile --profile-all --column-width 264 --memory-leak-detector True --html --outfile profile.html script.py
`

I'm getting the following output:

![image](https://github.com/plasma-umass/scalene/assets/8036389/b259c427-e66a-4bb4-91d5-c032c0616f49)

Looking at the earlier version of scalene (I guess <1.5.1, though I'm not 100% sure about the version), there used to be the following features:

1. The htmls were more interactive. Currently, all the graphs and plots in this html are static.
2. There is no OpenAI suggestion option.
3. There is no CPU/GPU option. But I reckon, _Time_ column is a representation of that.
4. I'm not able to run any multiprocessing code. I expect multiple columns in the output, each one showing the usage of each CPU core/GPU card. However, the above command never finishes when using mp module, and simply keeps on throwing the process id in the terminal.

Are there flags I'm missing out at the minute? 
**Note**: I've installed scalene inside a virtual environment, and happy to share more info as/when needed.

**Comment by emeryberger** [comment]
The problem is that you are using the (old) `--html` option which produces the HTML you see. That option predated the web UI, which you can run by running `scalene --viewer` and then loading a JSON profile (as produced by `--json --outfile profile.json`). If you are running Scalene locally, of course, you can just run `scalene your_prog.py` and it will automatically load the viewer and the profile from that run.
