### ISSUE TITLE
Is there a way to measure time spent in GC?

### ISSUE THREAD

**Issue by sarahec** [plasma-umass/scalene#791]
I'm benchmarking and performance tuning some ML code, and garbage collection seems to be the largest drag on performance. Is there a way to measure time spent in GC?

**Comment by emeryberger** [comment]
Not within Scalene. My intuition for GC in Python is that it's not usually a problem because most of the time I'd expect reference counting to handle most of the garbage (except for cycles, which I wouldn't expect in a case where you are using an ML library). I'd be interested to see what's going on! Anyway, looks like `py-spy` might be helpful here: see https://github.com/benfred/py-spy/issues/389.

**Comment by sarahec** [comment]
Thank you :) I'll keep looking.

**Comment by emeryberger** [comment]
Might try this, though it's not exactly the nicest UI:

https://stackoverflow.com/a/6115258/335756
