### ISSUE TITLE
Extra slow pytorch imports (~30s)

### ISSUE THREAD

**Issue by kpister** [plasma-umass/scalene#889]
**Describe the bug**
Pytorch related imports are taking an extra long time to resolve (15x longer?) when using scalene vs python.

**To Reproduce**
I have a simple test.py file, which is just `import torch`.
Run `scalene test.py`
Wait ~30s for report to finish
Run `python test.py`
Wait ~2s

**Screenshots**
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/1c792b53-0588-4c59-ba38-73ba33ea271e">

** Versions **
 - OS: debian 11
 - Python: 3.11.10
 - Scalene: 1.5.48
 - Torch: 2.5.1+cu121

I enabled gpu with scalene

**Comment by emeryberger** [comment]
Thanks for the report. We've been able to reproduce this locally and are looking into it.

**Comment by sternj** [comment]
Likewise reproduced, also with around a 50x slowdown.

**Comment by sternj** [comment]
I do not see this performance degradation at `5e457916606b1ebc`. Bisecting.

**Comment by sternj** [comment]
I've been looking into this more and the root problem has to do with how and when the interpreter calls the tracing function. 

At the moment, it seems that the C logic that decides when to disable the `PyEval_SetTrace` callback isn't properly disabling the callback in library calls. This is incurring a function call overhead unconditionally for every single event (opcode, line, call, and return) for every part of every library executed anywhere in the program. Since importing Pytorch invokes a lot of code, the function call overhead adds up incredibly quickly. 

I'm making headway on figuring out how precisely to do this disabling, CPython actually checks in several different places and manners to see whether a trace callback exists and whether to execute it. This is governed in both the `PyThreadState` struct and the `_PyCFrame` struct, with a lot of that happening in `ceval.c`. I think I'll have a solution by the end of tomorrow.

**Comment by emeryberger** [comment]
Verified that this fixes this problem (which turned out to be a bit thornier than anticipated). We've issued a new release that includes this fix. Thanks again for your report.
